hi_track/accounts/urls.py
from django.conf.urls import url, include
from .views import LoginView, LogOutView, ProfileView, PasswordChangeView, EmailConfirm, RegistrationView, PhoneConfirm

urlpatterns = [
    url(r'^confirm/$', EmailConfirm.as_view(), name="email_confirm"),
    url(r'^phone-confirm/$', PhoneConfirm.as_view(), name="phone_confirm"),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^profile/$', ProfileView.as_view(), name="profile"),
    url(r'^registration/$', RegistrationView.as_view(), name="registration"),
    url(r'^change-password/$', PasswordChangeView.as_view(), name="change_password"),
    # url(r'^reset-password/$', PasswordResetView.as_view(), name="reset_password"),
    # url(r'^reset-password-done/$', PasswordResetDoneView.as_view(), name="reset_password_done"),
    # url(r'^reset-password-confirm/(?P<token>[0-9A-Za-z_\-]+)/$', PasswordResetConfirmView.as_view(),
    #     name="reset_password_confirm"),
    url(r'^logout/$', LogOutView.as_view(), name="logout"),
]

hi_track/core/urls.py
from django.conf.urls import url, include

urlpatterns = [

]

hi_track/hi_track/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import TestTemplateView
from .health_check.views import HealthCheckAPIView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^core/', include("core.urls", namespace="core")),
    url(r'^accounts/', include("accounts.urls", namespace="accounts")),
    url(r'^notifications/', include("notifications.urls", namespace="notifications")),
    url(r'^customer-side/', include("customer_side.urls", namespace="customer_side")),
    url(r'^test/', TestTemplateView.as_view(), name="test"),

    url(r'^health-check/', HealthCheckAPIView.as_view(), name="health_check"),
]

hi_track/accounts/models.py
from django.core import validators
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.core.validators import RegexValidator
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .managers import CustomUserManager

USER_MODEL = settings.AUTH_USER_MODEL


class BaseUser(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(_('first name'), max_length=255, blank=True, null=True)
    last_name = models.CharField(_('last name'), max_length=255, blank=True, null=True)
    email = models.EmailField(_('email address'), max_length=255, unique=True, null=True, blank=True)
    phone_number = models.CharField(_('phone number'), max_length=25, unique=True)
    address = models.CharField(max_length=125, verbose_name=_("Address"), blank=True, null=True)

    is_staff = models.BooleanField(_('staff status'), default=False,
                                   help_text=_('Designates whether the user can log into this admin '
                                               'site.'))
    is_active = models.BooleanField(_('active'), default=True,
                                    help_text=_('Designates whether this user should be treated as '
                                                'active. Unselect this instead of deleting accounts.'))
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = CustomUserManager()

    USERNAME_FIELD = 'phone_number'

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = "{} {}".format(self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Returns the short name for the user."""
        return self.first_name

    @property
    def is_repairer(self):
        groups = [group.name for group in self.groups.all()]
        return 'repairer' in groups

    @property
    def is_service_center_manager(self):
        groups = [group.name for group in self.groups.all()]
        return 'service_center_manager' in groups

    @property
    def is_azercell_manager(self):
        groups = [group.name for group in self.groups.all()]
        return 'azercell_manager' in groups

    @property
    def is_customer(self):
        groups = [group.name for group in self.groups.all()]
        return 'customer' in groups

    def __str__(self):
        if self.first_name and self.last_name:
            return "{} {}".format(self.first_name, self.last_name)
        elif self.email:
            return self.email
        else:
            return str(self.phone_number)

hi_track/accounts/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.forms import ReadOnlyPasswordHashField, PasswordChangeForm, AuthenticationForm, \
    PasswordResetForm, SetPasswordForm
from django.contrib.auth import (
    get_user_model, password_validation,
    authenticate)
from base_tools.custom_filter_methods import get_or_none
# from .tasks import ResetPasswordSendEmailTask
import logging

logr = logging.getLogger(__name__)

User = get_user_model()


class BaseUserCreationForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given phone number and
    password.
    """
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }
    password1 = forms.CharField(label=_("Password"),
                                widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(label=_("Password confirmation"),
                                widget=forms.PasswordInput(attrs={'placeholder': 'Re-enter Password'}),
                                help_text=_("Enter the same password as above, for verification."))

    class Meta:
        model = User
        fields = ("email", "first_name", "last_name", "phone_number")

    def __init__(self, *args, **kwargs):
        super(BaseUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget = forms.TextInput(attrs={
            'placeholder': 'Email'})
        self.fields['first_name'].widget = forms.TextInput(attrs={
            'placeholder': 'First name'})
        self.fields['last_name'].widget = forms.TextInput(attrs={
            'placeholder': 'Last name'})
        self.fields['phone_number'].widget = forms.TextInput(attrs={
            'placeholder': 'Phone number *'})

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        password_validation.validate_password(self.cleaned_data.get('password2'), self.instance)
        return password2

    def save(self, commit=True):
        user = super(BaseUserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class BaseUserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField(label=_("Password"),
                                         help_text=_("Raw passwords are not stored, so there is no way to see "
                                                     "this user's password, but you can change the password "
                                                     "using <a href=\"../password/\">this form</a>."))

    class Meta:
        model = User
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(BaseUserChangeForm, self).__init__(*args, **kwargs)
        f = self.fields.get('user_permissions', None)
        if f is not None:
            f.queryset = f.queryset.select_related('content_type')

    def clean_password(self):
        return self.initial["password"]


class BaseUserRegistrationForm(BaseUserCreationForm):
    accept = forms.BooleanField(initial=False,
                                label=_('I have read and agree to the Terms of Service and Privacy Policy.'),
                                error_messages={'required': _('You must accept the rules')})


class BaseAuthenticationForm(AuthenticationForm):
    pass


class BaseUserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label=_("Old password"),
                                   widget=forms.PasswordInput())

    new_password1 = forms.CharField(label=_("New password"),
                                    widget=forms.PasswordInput(),
                                    )
    new_password2 = forms.CharField(label=_("Confirm new password"),
                                    widget=forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        super(BaseUserPasswordChangeForm, self).__init__(*args, **kwargs)
        self.fields['old_password'].widget = forms.PasswordInput(attrs={
            'placeholder': 'Old password:'})
        self.fields['new_password1'].widget = forms.PasswordInput(attrs={
            'placeholder': 'New password:'})
        self.fields['new_password2'].widget = forms.PasswordInput(attrs={
            'placeholder': 'Confirm new password:'})


class CustomSetPasswordForm(SetPasswordForm):
    pass


class ResetPasswordForm(forms.Form):
    email = forms.EmailField(label=_("Email"), max_length=254)
    phone_number = forms.EmailField(label=_("Email"), max_length=254)
    error_messages = {'unknown': _("This email address doesn't have an "
                                   "associated user account. Are you "
                                   "sure you've registered?")}

    def get_users(self, email):
        active_users = User.objects.filter(
            email__iexact=email, is_active=True)
        return (u for u in active_users if u.has_usable_password())

    def clean_email(self):
        email = self.cleaned_data['email']
        results = list(self.get_users(email))
        logr.debug(email)

        if not results:
            raise forms.ValidationError(self.error_messages['unknown'])
        return email

    # def save(self):
    #     email = self.cleaned_data["email"]
    #     task = ResetPasswordSendEmailTask()
    #     user = get_or_none(User, email=email)
    #     result = task.delay(user.pk).get()
    #     logr.debug(result)

hi_track/accounts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import RedirectView, FormView, TemplateView, CreateView, View
from django.http import HttpResponseBadRequest, HttpResponseForbidden, HttpResponse
from django.urls import reverse_lazy
from django.conf import settings
from django import forms as django_forms
from django.contrib.auth.models import Group
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from django.contrib.auth import get_user_model, authenticate, logout, login
from .forms import BaseAuthenticationForm, BaseUserPasswordChangeForm, BaseUserCreationForm
from .utils import logout_and_delete_other_sessions
from .tasks import SendActivationToUserEmailTask, SendActivationCodeToUserPhoneNumberTask
import redis

USER_MODEL = get_user_model()


class LoginView(FormView):
    form_class = BaseAuthenticationForm
    template_name = 'accounts/login.html'
    success_url = reverse_lazy("customer_side:repair_jobs_list")
    logout_url = reverse_lazy("accounts:logout")

    def form_valid(self, form):
        user = form.get_user()
        login(self.request, user)
        return super(LoginView, self).form_valid(form)

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect(self.success_url)
        return super(LoginView, self).get(request, *args, **kwargs)

    def get_success_url(self):
        next_url = self.request.GET.get('next', None)
        if next_url:
            if next_url == self.logout_url:
                return self.success_url
            return next_url
        else:
            return self.success_url


class LogOutView(LoginRequiredMixin, RedirectView):
    url = reverse_lazy("accounts:login")
    login_url = reverse_lazy("accounts:login")

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogOutView, self).get(request, *args, **kwargs)


class PasswordChangeView(LoginRequiredMixin, FormView):
    form_class = BaseUserPasswordChangeForm
    template_name = 'accounts/profile.html'
    success_url = reverse_lazy("accounts:login")
    login_url = reverse_lazy("accounts:login")

    def get_form_kwargs(self):
        kwargs = super(PasswordChangeView, self).get_form_kwargs()
        kwargs['user'] = self.get_user()
        return kwargs

    def get_user(self):
        return self.request.user

    def form_valid(self, form):
        form.save()
        logout_and_delete_other_sessions(self.request)
        return super(PasswordChangeView, self).form_valid(form)


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "accounts/profile.html"
    form_class = BaseUserPasswordChangeForm
    login_url = reverse_lazy("accounts:login")

    def get_context_data(self, **kwargs):
        context_data = super(ProfileView, self).get_context_data(**kwargs)
        context_data["form"] = self.form_class(self.request.GET)
        return context_data


class RegistrationView(CreateView):
    model = USER_MODEL
    form_class = BaseUserCreationForm
    template_name = "accounts/registration.html"
    success_url = reverse_lazy("accounts:phone_confirm")
    home_page = reverse_lazy("customer_side:repair_jobs_list")

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect(self.home_page)
        return super(RegistrationView, self).get(request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save()
        self.object.is_active = False
        self.object.save()
        group, created = Group.objects.get_or_create(name="customer")
        self.object.groups.add(group)
        if self.object.phone_number:
            send_activation = SendActivationCodeToUserPhoneNumberTask()
            send_activation.delay(self.object.pk)
        elif self.object.email:
            send_activation = SendActivationToUserEmailTask()
            send_activation.delay(self.object.pk)
        return super(RegistrationView, self).form_valid(form)


class EmailConfirm(View):
    success_url = reverse_lazy("accounts:login")

    # resend_url = reverse_lazy("account:resend_activation_key")

    def get(self, request):
        r = redis.Redis(connection_pool=settings.REDIS_POOL)
        try:
            activation_key = django_forms.CharField().clean(request.GET.get("activation"))
            email = r.get(activation_key)
            if email:
                confirm_user = USER_MODEL.objects.get(email=email.decode("utf-8"))
                if confirm_user.is_active:
                    return HttpResponseForbidden()
                else:
                    confirm_user.is_active = True
                    confirm_user.save()
                    r.delete(activation_key)
                    return redirect(self.success_url)
            else:
                pass
                # return redirect(self.resend_url)
        except (USER_MODEL.DoesNotExist, ValueError, django_forms.ValidationError):
            return HttpResponseBadRequest()


class PhoneConfirm(View):
    success_url = reverse_lazy("accounts:login")
    template_name = "accounts/confirm.html"

    # resend_url = reverse_lazy("account:resend_activation_key")

    def get(self, request):
        return render(request, self.template_name, {})

    def post(self, request):
        r = redis.Redis(connection_pool=settings.REDIS_POOL)
        try:
            activation_key = request.POST.get("activation")
            phone_number = r.get(activation_key)
            if phone_number:
                confirm_user = USER_MODEL.objects.get(phone_number=phone_number.decode("utf-8"))
                if confirm_user.is_active:
                    return redirect(self.success_url)
                else:
                    confirm_user.is_active = True
                    confirm_user.save()
                    r.delete(activation_key)
                    return redirect(self.success_url)
            else:
                pass
                # return redirect(self.resend_url)
        except (USER_MODEL.DoesNotExist, ValueError, django_forms.ValidationError):
            return HttpResponseBadRequest()

hi_track/accounts/templates/accounts/login.html
{% load staticfiles %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'hitrack/assets/images/favicon.png' %}">
    <title>Azercell - HiTrack</title>
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'hitrack/assets/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static 'hitrack/css/style.css' %}" rel="stylesheet">
    <!-- You can change the theme colors from here -->
    <link href="{% static 'hitrack/css/colors/blue.css' %}" id="theme" rel="stylesheet">
    <link href="{% static 'hitrack/css/custom.css' %}" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body class="fix-header card-no-border">
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <svg class="circular" viewBox="25 25 50 50">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" /> </svg>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper" class="fullheight">
        <!-- ============================================================== -->
        <!-- Topbar header - style you can find in pages.scss -->
        <!-- ============================================================== -->

        <!-- ============================================================== -->
        <!-- End Topbar header -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->

        <!-- ============================================================== -->
        <!-- End Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Page wrapper  -->
        <!-- ============================================================== -->
        <div class="login-wrap fullheight">
            <!-- ============================================================== -->
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container fullheight">
                <!-- ============================================================== -->
                <!-- Bread crumb and right sidebar toggle -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- End Bread crumb and right sidebar toggle -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- Start Page Content -->
                <!-- ============================================================== -->
<!--                 <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-block">
                                This is some text within a card block.
                            </div>
                        </div>
                    </div>
                </div> -->
                <div class="row fullheight">
                    <div class="col-xs-12 col-md-8 offset-md-2">
                        <div class="card">
                            <div class="card-block">
                            <h4 class="card-title text-center">LOGIN</h4>
                                <form class="form-horizontal form-material" method="post">{% csrf_token %}
                                    {% if form.non_field_errors %} <div class="alert alert-danger" role="alert">{{ form.non_field_errors }}</div> {% endif %}
                                    {% for field in form.visible_fields %}
                                        <div class="form-group">
                                            <label class="col-md-12">{{ field.label }}</label>
                                            <div class="col-md-12">
                                                {{ field|add_class:'form-control form-control-line' }}
                                            </div>
                                            {% if field.errors %}<span class="error">{{ field.errors.as_text }}</span>{% endif %}
                                        </div>
                                    {% endfor %}
                                    <div class="form-group">
                                        <div class="col-sm-12 text-center">
                                            <button class="btn btn-success" type="submit">Login</button>
                                        </div>
                                    </div>
                                    <!--<div class="form-group text-center">-->
                                        <!--<label for="forget"><a href="#" style="color:#c82727">Forgot Password?</a></label>-->
                                    <!--</div>-->
                                    <div class="form-group text-center">
                                        <label for="register"><a href="{% url 'accounts:registration' %}" style="color:#c82727">Register Now</a></label>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- ============================================================== -->
                <!-- End PAge Content -->
                <!-- ============================================================== -->
            </div>
            <!-- ============================================================== -->
            <!-- End Container fluid  -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- footer -->
            <!-- ============================================================== -->
   <!--          <footer class="footer text-center">
                © 2018 Barama Hackaton - Saf Usaqlar
            </footer> -->
            <!-- ============================================================== -->
            <!-- End footer -->
            <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- End Page wrapper  -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Wrapper -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    <script src="{% static 'hitrack/assets/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{% static 'hitrack/assets/plugins/bootstrap/js/tether.min.js' %}"></script>
    <script src="{% static 'hitrack/assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="{% static 'hitrack/js/jquery.slimscroll.js' %}"></script>
    <!--Wave Effects -->
    <script src="{% static 'hitrack/js/waves.js' %}"></script>
    <!--Menu sidebar -->
    <script src="{% static 'hitrack/js/sidebarmenu.js' %}"></script>
    <!--stickey kit -->
    <script src="{% static 'hitrack/assets/plugins/sticky-kit-master/dist/sticky-kit.min.js' %}"></script>
    <!--Custom JavaScript -->
    <script src="{% static 'hitrack/js/custom.min.js' %}"></script>
    <!-- ============================================================== -->
    <!-- Style switcher -->
    <!-- ============================================================== -->
    <script src="{% static 'hitrack/assets/plugins/styleswitcher/jQuery.style.switcher.js' %}"></script>
</body>

</html>

hi_track/accounts/templates/accounts/profile.html
{% extends "base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block page-content %}
    <div class="page-wrapper">
            <!-- ============================================================== -->
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Bread crumb and right sidebar toggle -->
                <!-- ============================================================== -->
                <div class="row page-titles">
                    <div class="col-md-6 col-8 align-self-center">
                        <h3 class="text-themecolor m-b-0 m-t-0">Profile</h3>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                            <li class="breadcrumb-item active">Profile</li>
                        </ol>
                    </div>
                </div>
                <!-- ============================================================== -->
                <!-- End Bread crumb and right sidebar toggle -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- Start Page Content -->
                <!-- ============================================================== -->
                <!-- Row -->
                <div class="row">
                    <!-- Column -->
                    <div class="col-lg-4 col-xlg-3 col-md-5">
                        <div class="card">
                            <div class="card-block">
                                <center class="m-t-30"> <img src="{% static 'hitrack/assets/images/users/5.png' %}" class="img-circle" width="150" />
                                    <h4 class="card-title m-t-10">
                                        {% if request.user.first_name %}
                                            {{ request.user.first_name }}
                                        {% else %}
                                            {{ request.user }}
                                        {% endif %}
                                    </h4>
                                </center>
                            </div>
                        </div>
                    </div>
                    <!-- Column -->
                    <!-- Column -->
                    <div class="col-lg-8 col-xlg-9 col-md-7">
                        <div class="card">
                            <div class="card-block">
                               <h4 class="card-title text-center">Change Password</h4>
                                <form class="form-horizontal form-material" method="post" action="{% url 'accounts:change_password' %}">{% csrf_token %}
                                    {% if form.non_field_errors %} <div class="alert alert-danger" role="alert">{{ form.non_field_errors }}</div> {% endif %}
                                    {% for field in form.visible_fields %}
                                        <div class="form-group">
                                            <div class="col-md-12">
                                                {{ field|add_class:'form-control form-control-line' }}
                                            </div>
                                            {% if field.errors %}<span class="error">{{ field.errors.as_text }}</span>{% endif %}
                                        </div>
                                    {% endfor %}
                                    <div class="form-group">
                                        <div class="col-sm-12 text-center">
                                            <button class="btn btn-success" type="submit">Change password</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <!-- Column -->
                </div>
                <!-- Row -->
                <!-- ============================================================== -->
                <!-- End PAge Content -->
                <!-- ============================================================== -->
            </div>
            <!-- ============================================================== -->
            <!-- End Container fluid  -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- footer -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- End footer -->
            <!-- ============================================================== -->
    </div>
{% endblock %}