hi_track/accounts/urls.py
from django.conf.urls import url, include
from .views import LoginView, LogOutView, ProfileView, PasswordChangeView, EmailConfirm, RegistrationView, PhoneConfirm

urlpatterns = [
    url(r'^confirm/$', EmailConfirm.as_view(), name="email_confirm"),
    url(r'^phone-confirm/$', PhoneConfirm.as_view(), name="phone_confirm"),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^profile/$', ProfileView.as_view(), name="profile"),
    url(r'^registration/$', RegistrationView.as_view(), name="registration"),
    url(r'^change-password/$', PasswordChangeView.as_view(), name="change_password"),
    # url(r'^reset-password/$', PasswordResetView.as_view(), name="reset_password"),
    # url(r'^reset-password-done/$', PasswordResetDoneView.as_view(), name="reset_password_done"),
    # url(r'^reset-password-confirm/(?P<token>[0-9A-Za-z_\-]+)/$', PasswordResetConfirmView.as_view(),
    #     name="reset_password_confirm"),
    url(r'^logout/$', LogOutView.as_view(), name="logout"),
]

hi_track/core/urls.py
from django.conf.urls import url, include

urlpatterns = [

]

hi_track/customer_side/urls.py
from django.conf.urls import url, include
from .views import RepairJobUpdateView, RepairJobListView, RepairAjaxView

urlpatterns = [
    url(r'^repair-jobs/$', RepairJobListView.as_view(), name="repair_jobs_list"),
    url(r'^repair-jobs/(?P<pk>[0-9]+)/$', RepairJobUpdateView.as_view(), name="repair_jobs_update"),
    url(r'^repair-jobs-ajax/(?P<pk>[0-9]+)/$', RepairAjaxView.as_view(), name="repair_jobs_ajax"),
]

hi_track/hi_track/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import TestTemplateView
from .health_check.views import HealthCheckAPIView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^core/', include("core.urls", namespace="core")),
    url(r'^accounts/', include("accounts.urls", namespace="accounts")),
    url(r'^notifications/', include("notifications.urls", namespace="notifications")),
    url(r'^customer-side/', include("customer_side.urls", namespace="customer_side")),
    url(r'^test/', TestTemplateView.as_view(), name="test"),

    url(r'^health-check/', HealthCheckAPIView.as_view(), name="health_check"),
]

hi_track/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'hitrack/assets/images/favicon.png' %}">
    <title>Azercell - HiTrack</title>
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'hitrack/assets/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static 'hitrack/css/style.css' %}" rel="stylesheet">
    <!-- You can change the theme colors from here -->
    <link href="{% static 'hitrack/css/colors/blue.css' %}" id="theme" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body class="fix-header card-no-border">
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <svg class="circular" viewBox="25 25 50 50">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" /> </svg>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper">
        <!-- ============================================================== -->
        <!-- Topbar header - style you can find in pages.scss -->
        <!-- ============================================================== -->
        <header class="topbar">
            <nav class="navbar top-navbar navbar-toggleable-sm navbar-light">
                <!-- ============================================================== -->
                <!-- Logo -->
                <!-- ============================================================== -->
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'customer_side:repair_jobs_list' %}">
                        <!-- Logo icon -->
                        <b>
                            <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                            <!-- Dark Logo icon -->
                            <img src="{% static 'hitrack/assets/images/logo-icon.png' %}" alt="homepage" class="dark-logo" style="height: 45px;" />

                        </b>
                        <!--End Logo icon -->
                        <!-- Logo text -->
                        <span>
                            <!-- dark Logo text -->
                           hiTrack
                        </span>
                    </a>
                </div>
                <!-- ============================================================== -->
                <!-- End Logo -->
                <!-- ============================================================== -->
                <div class="navbar-collapse">
                    <!-- ============================================================== -->
                    <!-- toggle and nav items -->
                    <!-- ============================================================== -->
                    <ul class="navbar-nav mr-auto mt-md-0 ">
                        <!-- This is  -->
                        <li class="nav-item"> <a class="nav-link nav-toggler hidden-md-up text-muted waves-effect waves-dark" href="javascript:void(0)"><i class="ti-menu"></i></a> </li>
                    </ul>
                    <!-- ============================================================== -->
                    <!-- User profile and search -->
                    <!-- ============================================================== -->
                    <ul class="navbar-nav my-lg-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="{% static 'hitrack/assets/images/users/5.png' %}" alt="user" class="profile-pic m-r-5" />{{ request.user }}</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
                        </div>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- ============================================================== -->
        <!-- End Topbar header -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        <aside class="left-sidebar">
            <!-- Sidebar scroll-->
            <div class="scroll-sidebar">
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav">
                    <ul id="sidebarnav">
                        <li>
                            <a href="{% url 'accounts:profile' %}" class="waves-effect"><i class="fa fa-user m-r-10" aria-hidden="true"></i>Profile</a>
                        </li>
                        <li>
                            <a href="{% url 'customer_side:repair_jobs_list' %}" class="waves-effect"><i class="fa fa-bar-chart-o m-r-10" aria-hidden="true"></i>Repair information</a>
                        </li>
                    </ul>
                </nav>
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
        </aside>

        {% block page-content %}
        {% endblock %}
        <!-- ============================================================== -->
        <!-- End Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Page wrapper  -->
        <!-- ============================================================== -->

        <!-- ============================================================== -->
        <!-- End Page wrapper  -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Wrapper -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    <script src="{% static 'hitrack/assets/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{% static 'hitrack/assets/plugins/bootstrap/js/tether.min.js' %}"></script>
    <script src="{% static 'hitrack/assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="{% static 'hitrack/js/jquery.slimscroll.js' %}"></script>
    <!--Wave Effects -->
    <script src="{% static 'hitrack/js/waves.js' %}"></script>
    <!--Menu sidebar -->
    <script src="{% static 'hitrack/js/sidebarmenu.js' %}"></script>
    <!--stickey kit -->
    <script src="{% static 'hitrack/assets/plugins/sticky-kit-master/dist/sticky-kit.min.js' %}"></script>
    <!--Custom JavaScript -->
    <script src="{% static 'hitrack/js/custom.min.js' %}"></script>
    <script src="{% static 'hitrack/js/ajaxrf.js' %}"></script>
    <script src="{% static 'hitrack/js/myajax.js' %}"></script>

    <!-- ============================================================== -->
    <!-- Style switcher -->
    <!-- ============================================================== -->
    <script src="{% static 'hitrack/assets/plugins/styleswitcher/jQuery.style.switcher.js' %}"></script>
</body>

</html>