hi_track/core/urls.py
from django.conf.urls import url, include

urlpatterns = [

]

hi_track/customer_side/urls.py
from django.conf.urls import url, include
from .views import RepairJobUpdateView, RepairJobListView, RepairAjaxView

urlpatterns = [
    url(r'^repair-jobs/$', RepairJobListView.as_view(), name="repair_jobs_list"),
    url(r'^repair-jobs/(?P<pk>[0-9]+)/$', RepairJobUpdateView.as_view(), name="repair_jobs_update"),
    url(r'^repair-jobs-ajax/(?P<pk>[0-9]+)/$', RepairAjaxView.as_view(), name="repair_jobs_ajax"),
]

hi_track/hi_track/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import TestTemplateView
from .health_check.views import HealthCheckAPIView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^core/', include("core.urls", namespace="core")),
    url(r'^accounts/', include("accounts.urls", namespace="accounts")),
    url(r'^notifications/', include("notifications.urls", namespace="notifications")),
    url(r'^customer-side/', include("customer_side.urls", namespace="customer_side")),
    url(r'^test/', TestTemplateView.as_view(), name="test"),

    url(r'^health-check/', HealthCheckAPIView.as_view(), name="health_check"),
]

hi_track/customer_side/models.py
from django.db import models

# Create your models here.

hi_track/customer_side/forms.py
from django import forms
from core.models import RepairJob


class RepairJobForm(forms.ModelForm):
    class Meta:
        model = RepairJob
        fields = ("confirmed_by_owner", "rate", "comment")

hi_track/customer_side/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import APIView
from rest_framework.renderers import TemplateHTMLRenderer, JSONRenderer
from django.http.response import HttpResponse, JsonResponse

import json
from rest_framework.response import Response
from rest_framework import status
from django.views.generic import View, UpdateView, ListView
from django.core.urlresolvers import reverse, reverse_lazy
from core.models import RepairJob
from customer_side.forms import RepairJobForm
from base_tools.custom_filter_methods import get_or_none
import logging

logger = logging.getLogger(__name__)


class RepairJobListView(LoginRequiredMixin, ListView):
    model = RepairJob
    paginate_by = 10
    template_name = "customer_side/repair-info-list.html"
    login_url = reverse_lazy("accounts:login")
    context_object_name = "repair_jobs"

    def get_queryset(self):
        repair_jobs = self.model.objects.filter(owner=self.request.user)
        return repair_jobs


class RepairJobUpdateView(LoginRequiredMixin, UpdateView):
    model = RepairJob
    form_class = RepairJobForm
    template_name = "customer_side/repair-detail.html"
    login_url = reverse_lazy("accounts:login")
    success_url = reverse_lazy("customer_side:repair_jobs_list")
    context_object_name = "repair"
    renderer_classes = (JSONRenderer, TemplateHTMLRenderer)

    def get_queryset(self):
        repair_jobs = self.model.objects.filter(owner=self.request.user)
        return repair_jobs

    def put(self, request, pk):
        json_str = request.body.decode(encoding='UTF-8')
        data = json.loads(json_str)
        obj = get_object_or_404(RepairJob, pk=pk)
        logger.info('Repair Job Update {} {}'.format(data, obj))
        if data.get("rate"):
            obj.rate = data.get("rate")
        if data.get("comment"):
            obj.comment = data.get("comment")
        if data.get("confirmed_by_owner"):
            obj.confirmed_by_owner = data.get("confirmed_by_owner")
        obj.save()
        response = JsonResponse(status=200, data={'message': 'success'})
        # response.accepted_renderer = JSONRenderer
        # response.accepted_media_type =
        return response
        # try:
        #
        # except:
        #     return HttpResponse(status=400, content_type="application/json")


class RepairAjaxView(LoginRequiredMixin, View):

    def put(self, request, pk):
        try:
            json_str = request.body.decode(encoding='UTF-8')
            data = json.loads(json_str)
            obj = get_object_or_404(RepairJob, pk=pk)
            if data.get("rate"):
                obj.rate = data.get("rate")
            if data.get("comment"):
                obj.comment = data.get("comment")
            if data.get("confirmed_by_owner"):
                obj.confirmed_by_owner = data.get("confirmed_by_owner")
            return Response(status=status.HTTP_200_OK)
        except:
            return HttpResponse(status=400, content_type="application/json")

hi_track/customer_side/templates/customer_side/pagination.html
<ul class="pagination pull-right">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
    {% endif %}
    {% for page_number in paginator.page_range %}
        {% if page_number == page_obj.number %}
          <li class="page-item active">
            <a class="page-link">
              {{ page_number }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">
              {{ page_number }}
            </a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
    {% endif %}
</ul>

hi_track/customer_side/templates/customer_side/repair-detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block page-content %}
<div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="row page-titles">
            <div class="col-md-6 col-8 align-self-center">
                <h3 class="text-themecolor m-b-0 m-t-0">Info</h3>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                    <li class="breadcrumb-item active">info</li>
                </ol>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        {% if repair %}
        <div class="row get-data" data-value="{% url 'customer_side:repair_jobs_update' repair.pk %}">
            <!-- column -->
            <div class="col-sm-7 col-md-7">
                <div class="card">
                    <div class="card-block">
                        <p>
                            Azercell Center : {{ repair.azercell_center }}
                        </p>
                        <p>
                            Problem: <span>{{ repair.problem_title }}</span>
                        </p>
                        <p>
                            Device: <span>{{ repair.device }}</span>
                        </p>
                        <p>
                            <span>{{ repair.description }}</span>
                        </p>
                        <p>
                            <code>
                                Request date: <span>{{ repair.created_at }}</span>
                            </code>
                        </p>
                        {% if repair.cost %}
                            <p>
                                Cost: <span>{{ repair.cost }} AZN</span>
                            </p>
                        {% endif %}
                        {% if not repair.confirmed_by_owner %}
                        <form action="" class="clearfix">
                            <div class="col-sm-12 text-center">
                                <button class="btn btn-success agreed pull-right">I agree</button>
                            </div>
                        </form>
                        {% endif %}
                        <div class="agreed-box"></div>
                        {% if repair.timeline_set.all %}
                        <aside class="trackDetailWrapper">

                            <ul class="trackDetail">
                                {% for timeline in repair.timeline_set.all %}
                                <li>
                                    <span class="track-status">{{ timeline.repair_status }}</span>
                                    <span class="track-circle circle-1"></span>
                                    <span class="track-date">{{ timeline.created_at }}</span>
                                </li>
                                {% endfor %}
                            </ul>

                        </aside>
                        <div class="clearfix">
                            <i class="fa fa-2x fa-arrows-h pull-right"></i>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-md-5">
                <div class="card">
                    <div class="card-block">
                        <aside class="rate-stars">
                            <label for="rate">Rate</label>
                            {% for x in "*****"%}
                            {% if repair.rate >= forloop.counter %}
                            <span data-rate="{{forloop.counter}}" class="fa fa-star checked"></span>
                            {% else %}
                            <span data-rate="{{forloop.counter}}" class="fa fa-star"></span>
                            {% endif %}
                            {% endfor %}
                        </aside>
                        <form class="form-horizontal form-material">
                            <div class="form-group">
                                <label class="col-md-12"></label>
                                <div class="col-md-12">
                                    <textarea name="" id="comment" cols="30" rows="2" placeholder="Comment"
                                              class="form-control form-control-line"></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-12 text-center">
                                    <button class="btn btn-success send-comment pull-right">Send</button>
                                </div>
                            </div>
                        </form>
                        <div class="comments">
                            <p class="comment-box"></p>
                            <p style="float: right">
                                {% if repair.comment %}
                            <h3>Your comment</h3>
                            <p class="user-comment">{{ repair.comment }}</p>
                            {% endif %}
                            </h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- End footer -->
    <!-- ============================================================== -->
</div>
{% endblock %}

hi_track/customer_side/templates/customer_side/repair-info-list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block page-content %}
    <div class="page-wrapper">
            <!-- ============================================================== -->
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Bread crumb and right sidebar toggle -->
                <!-- ============================================================== -->
                <div class="row page-titles">
                    <div class="col-md-6 col-8 align-self-center">
                        <h3 class="text-themecolor m-b-0 m-t-0">Info</h3>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                            <li class="breadcrumb-item active">info</li>
                        </ol>
                    </div>
                </div>
                <!-- ============================================================== -->
                <!-- End Bread crumb and right sidebar toggle -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- Start Page Content -->
                <!-- ============================================================== -->
                <div class="row">
                    <!-- column -->
                    <div class="col-sm-12">
                        <div class="card">
                            <div class="card-block">
                                <div class="table-responsive">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Azercell center</th>
                                                <th>Problem title</th>
                                                <th>Problem type</th>
                                                <th>Device</th>
                                                <th>Current Status</th>
                                                <th>Cost</th>
                                                <th>Detail</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for r in repair_jobs %}
                                                <tr>
                                                    <td>{{ r.azercell_center }}</td>
                                                    <td>{{ r.problem_title }}</td>
                                                    <td>{{ r.problem_type|default_if_none:"other" }}</td>
                                                    <td>{{ r.device.name }}({{ r.device.device_type }})</td>
                                                    <td><code>{{ r.current_status }}</code></td>
                                                    <td>{{ r.cost }}</td>
                                                    <td><a class="get-more" href="{% url 'customer_side:repair_jobs_update' r.id %}">more</a></td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                                <nav aria-label="Page navigation">
                                    {% if repair_jobs %}
                                        {% include "customer_side/pagination.html" %}
                                    {% endif %}
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- ============================================================== -->
                <!-- End PAge Content -->
                <!-- ============================================================== -->
            </div>
            <!-- ============================================================== -->
            <!-- End Container fluid  -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- footer -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- End footer -->
            <!-- ============================================================== -->
    </div>
{% endblock %}